POST http://localhost:3001/api/patients HTTP/1.1
Content-Type: application/json

{
  "name": "John Doe",
  "ssn": "123456-1234",
  "dateOfBirth": "1980-04-02",
  "gender": "male",
  "occupation": "gardener"
}
